name: Test build

on:
  push:

  pull_request:

  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: npm install
        run: npm install
      - name: npm fund
        run: npm fund
      - name: Test with roboter
        run: npx roboter
